## 

In [1]:
import pandas as pd

In [2]:
fruits = pd.read_csv("../Data/fruits.csv")
fruits.head()

,length,weight,name
0,25.4,242.0,apple
1,26.3,290.0,apple
2,26.5,340.0,apple
3,29.0,363.0,apple
4,29.0,430.0,apple


### Feature Set과 Target Set를 Numpy Array로 변경

In [3]:
import numpy as np

----
#### 연습

In [27]:
# numpy의 column stack과 row stack
testA = np.array([1,2,3,4])
testB = np.array([10,20,30,40])

# 2개의 Array를 묶어서 컬럼기반 Array로 만들기
combineA = [[i,j]for i,j in zip(testA, testB)]
print(np.array(combineA))
print("-" * 50)

# numpy에서 컬럼 기반 
combineB = np.column_stack((testA, testB))
print(combineB)
print("-" * 50)

# numpy에서 Data 
combineD = np.hstack((testA, testB))
print(combineD)
print("-" * 50)

# numpy에서 index 기반
combineC = np.vstack((testA,testB))
print(combineC)
print("-" * 50)

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]]
--------------------------------------------------
[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]]
--------------------------------------------------
[ 1  2  3  4 10 20 30 40]
--------------------------------------------------
[[ 1  2  3  4]
 [10 20 30 40]]
--------------------------------------------------


In [12]:
# List Comperhension
test1 = []

# 1)
for i in range(1,10+1):
   test1.append(i)

# 2) 1번의 내용과 동일하게 적은 것
test1 = [i for i in range (1,10+1) if i%2 == 0]
test1

[2, 4, 6, 8, 10]

In [25]:
# fruits와 feature
fruits_data = np.column_stack((fruits.length, fruits.weight))
fruits_data[:5]

array([[ 25.4, 242. ],
       [ 26.3, 290. ],
       [ 26.5, 340. ],
       [ 29. , 363. ],
       [ 29. , 430. ]])

In [26]:
fruits_data.shape

(49, 2)

In [28]:
# Target
fruits_target = np.array(fruits.name)
fruits_target[:5]


array(['apple', 'apple', 'apple', 'apple', 'apple'], dtype=object)